package org.itantra.proto

import java.security.SecureRandom
import java.util.Base64

/**
 * The contents of a pairing QR code. Task **W6.11**, `docs/SECURITY.md` section 8.
 *
 * ## What a pairing code is
 *
 * The whole trust establishment, in one scan: the shared key, the identifiers needed to
 * use it, and the template profile digest so two handsets discover a mismatch before
 * either speaks the wrong sentence from the same byte (risk S-06).
 *
 * ```
 *  iT1:<base64url key>:<keyId>:<profileId>:<profileDigest>:<tagBits>:<node>:<expiry>
 * ```
 *
 * ## Three rules, and each closes a specific hole
 *
 * **It expires after 120 seconds.** A photograph of a screen is a key otherwise. Two
 * minutes is long enough to hold two handsets together and short enough that a picture
 * taken across a room is worthless by the time it is used. [isExpired] fails **closed**:
 * a code with no readable expiry, or one from the future, is rejected rather than
 * accepted on the benefit of the doubt.
 *
 * **The key never reaches disk.** This class parses into memory and the caller puts the
 * key straight into Android Keystore. [toString] is overridden so the key cannot reach a
 * log, a crash report or a debugger view through the ordinary route — the single most
 * likely way key material escapes is not an attacker, it is a developer printing an
 * object (risk S-04).
 *
 * **The key is generated by [SecureRandom].** Not `Random`, whose output is predictable
 * from a few samples.
 */
class PairingCode(
    /** 32 bytes. Copied on the way in and out, so no caller holds a reference to ours. */
    key: ByteArray,
    val keyId: Int,
    val profileId: String,
    val profileDigest: ByteArray,
    val tagBits: Int,
    val nodeId: Int,
    val expiresAtMillis: Long,
) {
    private val keyBytes = key.copyOf()

    init {
        require(key.size == KEY_BYTES) { "key must be $KEY_BYTES bytes, was ${key.size}" }
        require(keyId in 0..0xFF) { "keyId must fit 8 bits: $keyId" }
        require(nodeId in 0..0xFF) { "nodeId must fit 8 bits: $nodeId" }
        require(tagBits in setOf(64, 96, 128)) { "implausible tag length: $tagBits" }
        require(profileDigest.size == TemplateTable.DIGEST_BYTES) {
            "profile digest must be ${TemplateTable.DIGEST_BYTES} bytes"
        }
    }

    /**
     * A copy, so callers cannot mutate the code's own key, and so a caller that zeroes
     * its copy after loading it into Keystore does not corrupt this one.
     */
    fun key(): ByteArray = keyBytes.copyOf()

    /**
     * Overwrites the key in memory.
     *
     * Best effort — the JVM may have copied it during a garbage collection — but it
     * shortens the window in which a heap dump yields the key, and it costs nothing.
     */
    fun destroy() = keyBytes.fill(0)

    fun isExpired(nowMillis: Long): Boolean = nowMillis >= expiresAtMillis

    fun secondsRemaining(nowMillis: Long): Long = ((expiresAtMillis - nowMillis) / 1_000).coerceAtLeast(0)

    /** The string that goes into the QR image. */
    fun encode(): String =
        listOf(
            PREFIX,
            B64.encodeToString(keyBytes),
            keyId.toString(),
            profileId,
            B64.encodeToString(profileDigest),
            tagBits.toString(),
            nodeId.toString(),
            expiresAtMillis.toString(),
        ).joinToString(SEPARATOR)

    /**
     * Deliberately does **not** include the key.
     *
     * The most likely way key material escapes is not an attacker but a developer
     * logging an object, so the ordinary route is closed at the source.
     */
    override fun toString(): String = "PairingCode(keyId=$keyId, node=$nodeId, profile=$profileId, key=<redacted>)"

    companion object {
        const val PREFIX = "iT1"
        const val SEPARATOR = ":"
        const val KEY_BYTES = 32
        const val VALIDITY_MILLIS = 120_000L

        private val B64: Base64.Encoder = Base64.getUrlEncoder().withoutPadding()
        private val B64_DECODE: Base64.Decoder = Base64.getUrlDecoder()

        /** Generates a fresh code with a `SecureRandom` key, valid for 120 seconds. */
        fun generate(
            keyId: Int,
            profileId: String,
            profileDigest: ByteArray,
            nodeId: Int,
            nowMillis: Long,
            tagBits: Int = 128,
            random: SecureRandom = SecureRandom(),
        ): PairingCode {
            val key = ByteArray(KEY_BYTES).also { random.nextBytes(it) }
            return PairingCode(
                key = key,
                keyId = keyId,
                profileId = profileId,
                profileDigest = profileDigest,
                tagBits = tagBits,
                nodeId = nodeId,
                expiresAtMillis = nowMillis + VALIDITY_MILLIS,
            ).also { key.fill(0) }
        }

        /**
         * Parses a scanned code.
         *
         * @return null for anything malformed. A camera reads whatever is put in front of
         *   it, including a QR code from a poster, so this is untrusted input in the
         *   strictest sense and every failure is silent rather than diagnostic — a parser
         *   that explains precisely why it rejected something is an oracle.
         */
        fun decode(
            text: String,
            nowMillis: Long,
        ): PairingCode? {
            val parts = text.trim().split(SEPARATOR)
            if (parts.size != FIELD_COUNT) return null
            if (parts[0] != PREFIX) return null

            return try {
                val code =
                    PairingCode(
                        key = B64_DECODE.decode(parts[1]),
                        keyId = parts[2].toInt(),
                        profileId = parts[3],
                        profileDigest = B64_DECODE.decode(parts[4]),
                        tagBits = parts[5].toInt(),
                        nodeId = parts[6].toInt(),
                        expiresAtMillis = parts[7].toLong(),
                    )
                // Fails closed: an expired code, or one claiming to be valid for longer
                // than the rules allow, is refused rather than trusted.
                when {
                    code.isExpired(nowMillis) -> null
                    code.expiresAtMillis - nowMillis > VALIDITY_MILLIS -> null
                    else -> code
                }
            } catch (malformed: Exception) {
                null
            }
        }

        private const val FIELD_COUNT = 8
    }
}
