package org.itantra.app.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.itantra.bench.LatencySummary
import org.itantra.bench.StageSummary
import org.itantra.bench.UtteranceTrace

/**
 * The metrics screen. Task **W8.1**.
 *
 * ## Why an operational product carries a metrics screen at all
 *
 * Because the alternative is a slide. Every latency and compression figure in this
 * submission is generated by the code that produced it, and this screen is where a jury
 * can watch that happen rather than take it on trust — press the button, speak, and see the
 * number move. A figure that can be reproduced in the room is worth more than a figure that
 * was measured properly last week.
 *
 * ## The screen refuses to quote an unreportable figure
 *
 * `docs/EVALUATION.md` section 1 asks for a hundred utterances minimum, median and p95,
 * never a single run. Below that this screen shows the sample count and the words *not
 * reportable* instead of a number — because a plausible-looking millisecond figure on a
 * device screen is exactly the sort of thing that gets photographed and quoted, and by then
 * nobody remembers it came from nine utterances on a cold handset.
 *
 * That refusal is the feature. It costs nothing when the run is real.
 *
 * ## Three views, because one number cannot carry the argument
 *
 * The headline median answers "how fast". The **stage table** answers "where did the time
 * go", which is what makes a slow run actionable — a slow decode is a thermal problem and a
 * slow link is a radio problem, and they have opposite remedies. The **histogram** answers
 * "is it consistent", and it is the only one of the three that can show a bimodal run: two
 * hundred utterances clustered at 900 ms and 1 800 ms have a respectable median and a
 * throttling defect, and the table alone would hide it.
 */
@Composable
fun MetricsScreen(
    traces: List<UtteranceTrace>,
    onExportCsv: () -> Unit,
    /**
     * What the last export did, or why it refused.
     *
     * The export used to set a status the operator could not see: it lands in the shared
     * pack-status string, which only the storage screen rendered. Pressing EXPORT CSV here
     * therefore looked exactly like the empty lambda it had just replaced -- a control that
     * takes a press and shows nothing. Most presses are refusals, and the refusal *is* the
     * useful output, so it has to appear on the screen the button is on.
     */
    status: String? = null,
    modifier: Modifier = Modifier,
) {
    val p = palette
    val summary = LatencySummary.of(traces)
    val reportable = LatencySummary.isReportable(traces)
    val completed = traces.count { it.endToEndMillis != null }

    Column(
        modifier
            .fillMaxSize()
            .background(p.ground)
            .verticalScroll(rememberScrollState()),
    ) {
        Row(
            Modifier
                .fillMaxWidth()
                .background(p.paper)
                .padding(start = 16.dp, end = 16.dp, top = 12.dp, bottom = 12.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text("Metrics", fontSize = Tokens.Title, fontWeight = FontWeight.Bold, color = p.ink)
            Spacer(Modifier.weight(1f))
            Mono("$completed utterances", p.muted)
        }
        Box(Modifier.fillMaxWidth().height(Tokens.Hairline).background(p.hairline))

        if (completed == 0) {
            EmptyState(
                icon = Icons.Chart,
                title = "Nothing measured yet",
                body = "Send one utterance and the strip fills.",
                family = p.sky,
            )
            return@Column
        }

        Column(
            Modifier.padding(horizontal = 12.dp, vertical = 14.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            Headline(summary, reportable, completed, traces)
            StageTable(traces)
            ExportRow(onExportCsv)
            status?.let {
                Text(
                    it,
                    fontSize = Tokens.Label,
                    lineHeight = Tokens.Label * 1.4f,
                    color = p.muted,
                    modifier = Modifier.padding(horizontal = 4.dp),
                )
            }
        }
    }
}

/** A figure or a machine fact, in the one face this screen sets numbers in. */
@Composable
private fun Mono(
    text: String,
    colour: Color,
    size: androidx.compose.ui.unit.TextUnit = Tokens.Instrument,
    weight: FontWeight = FontWeight.Medium,
) {
    Text(text, fontSize = size, fontFamily = FontFamily.Monospace, fontWeight = weight, color = colour)
}

/**
 * The headline card, or the reason there isn't one.
 *
 * Median **and** p95 together, never the median alone: an operator remembers the slowest
 * exchange, not the average one, and a median quoted by itself is the number that makes a
 * system look better than it feels. The median is set at 38 sp and the other two at 22 sp
 * because one of the three is the answer and two are the caveat — a row of three equal
 * figures says the opposite.
 */
@Composable
private fun Headline(
    summary: LatencySummary.Stats?,
    reportable: Boolean,
    completed: Int,
    traces: List<UtteranceTrace>,
) {
    val p = palette
    if (summary == null || !reportable) {
        // The refusal has to look deliberate and expensive rather than like a bug. It is
        // this screen's best argument for every other number on it.
        Column(
            Modifier
                .fillMaxWidth()
                .background(p.paper, RoundedCornerShape(Tokens.RadiusTile))
                .border(Tokens.SignalBorder, p.butter.mid, RoundedCornerShape(Tokens.RadiusTile))
                .padding(16.dp)
                .semantics(mergeDescendants = true) {
                    contentDescription =
                        "Not reportable. $completed of " +
                        "${LatencySummary.MINIMUM_UTTERANCES} utterances collected."
                },
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                Icon(
                    Icons.Hourglass,
                    contentDescription = null,
                    tint = p.butter.core,
                    modifier = Modifier.size(20.dp),
                )
                Text(
                    "NOT REPORTABLE",
                    fontSize = Tokens.BodySmall,
                    fontWeight = FontWeight.Bold,
                    color = p.butter.deep,
                )
            }
            Text(
                "$completed of ${LatencySummary.MINIMUM_UTTERANCES} utterances. " +
                    "A median over fewer is not a median.",
                fontSize = Tokens.Label,
                lineHeight = Tokens.Label * 1.45f,
                color = p.muted,
            )
            Box(
                Modifier
                    .fillMaxWidth()
                    .height(6.dp)
                    .background(p.sunken, RoundedCornerShape(Tokens.RadiusPill)),
            ) {
                Box(
                    Modifier
                        .fillMaxWidth(
                            (completed.toFloat() / LatencySummary.MINIMUM_UTTERANCES).coerceIn(0f, 1f),
                        )
                        .height(6.dp)
                        .background(p.butter.core, RoundedCornerShape(Tokens.RadiusPill)),
                )
            }
        }
        return
    }

    Column(
        Modifier
            .fillMaxWidth()
            .background(p.paper, RoundedCornerShape(Tokens.RadiusTile))
            .border(Tokens.Hairline, p.hairline, RoundedCornerShape(Tokens.RadiusTile))
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(14.dp),
    ) {
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
            Mono("END TO END", p.muted)
            Mono("target 800-1200", p.muted)
        }
        Row(
            Modifier.fillMaxWidth().semantics(mergeDescendants = true) {
                contentDescription =
                    "Median ${summary.medianMillis} milliseconds, " +
                    "p95 ${summary.p95Millis}, worst ${summary.worstMillis}."
            },
            verticalAlignment = Alignment.Bottom,
            horizontalArrangement = Arrangement.spacedBy(16.dp),
        ) {
            Column(Modifier.weight(1f)) {
                Mono("${summary.medianMillis}", p.sky.deep, Tokens.Display, FontWeight.Bold)
                Text("MEDIAN ms", fontSize = Tokens.Instrument, color = p.muted)
            }
            Box(Modifier.size(width = 1.dp, height = 44.dp).background(p.hairline))
            Column {
                Mono("${summary.p95Millis}", p.ink, Tokens.Figure, FontWeight.Bold)
                Text("P95", fontSize = Tokens.Instrument, color = p.muted)
            }
            Column {
                Mono("${summary.worstMillis}", p.ink, Tokens.Figure, FontWeight.Bold)
                Text("WORST", fontSize = Tokens.Instrument, color = p.muted)
            }
        }
        Histogram(traces, summary.p95Millis)
    }
}

/**
 * The distribution as bars, with the p95 marked where it falls.
 *
 * Drawn with sized boxes rather than a charting library: the data is already bucketed, and a
 * dependency here would be carried into an APK that constraint **N2** caps at thirty
 * megabytes, for the sake of one diagnostic chart. The modal bucket is the only one in the
 * signal colour — a chart where every bar is the accent has no accent.
 */
@Composable
private fun Histogram(
    traces: List<UtteranceTrace>,
    p95: Long?,
) {
    val p = palette
    val buckets = StageSummary.histogram(traces)
    if (buckets.isEmpty()) return
    val tallest = buckets.maxOf { it.count }.coerceAtLeast(1)
    val busiest = buckets.maxByOrNull { it.count }

    Column(
        Modifier.fillMaxWidth().semantics(mergeDescendants = true) {
            // A bar chart read glyph by glyph is noise. The shape, in one sentence.
            contentDescription =
                busiest?.let {
                    "Distribution over ${buckets.sumOf { b -> b.count }} utterances, " +
                        "most between ${it.fromMillis} and ${it.toMillis} milliseconds."
                } ?: "No distribution yet."
        },
        verticalArrangement = Arrangement.spacedBy(6.dp),
    ) {
        Row(
            Modifier.fillMaxWidth().height(92.dp),
            verticalAlignment = Alignment.Bottom,
            horizontalArrangement = Arrangement.spacedBy(3.dp),
        ) {
            buckets.forEach { bucket ->
                val modal = bucket === busiest && bucket.count > 0
                val past95 = p95 != null && bucket.fromMillis >= p95
                Box(
                    Modifier
                        .weight(1f)
                        .fillMaxHeight((bucket.count.toFloat() / tallest).coerceIn(0.02f, 1f))
                        .background(
                            when {
                                modal -> p.sky.core
                                past95 -> p.butter.mid
                                else -> p.sky.mid
                            },
                            RoundedCornerShape(topStart = 3.dp, topEnd = 3.dp),
                        ),
                )
            }
        }
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
            Mono("${buckets.first().fromMillis}", p.muted)
            p95?.let { Mono("p95 $it", p.butter.core) }
            Mono("${buckets.last().toMillis} ms", p.muted)
        }
    }
}

/** One row per stage, with the budget beside it so a reader need not know it. */
@Composable
private fun StageTable(traces: List<UtteranceTrace>) {
    val p = palette
    val stages = StageSummary.byStage(traces)
    if (stages.isEmpty()) return

    Column(
        Modifier
            .fillMaxWidth()
            .background(p.paper, RoundedCornerShape(Tokens.RadiusTile))
            .border(Tokens.Hairline, p.hairline, RoundedCornerShape(Tokens.RadiusTile)),
    ) {
        Row(
            Modifier
                .fillMaxWidth()
                .heightIn(min = 42.dp)
                .background(p.ground)
                .padding(horizontal = 14.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Mono("BY STAGE", p.muted)
            Spacer(Modifier.weight(1f))
            Mono("median", p.muted)
        }
        stages.forEach { stat ->
            val budget = "${stat.stage.budgetMillis.first}-${stat.stage.budgetMillis.last} ms"
            Box(Modifier.fillMaxWidth().height(1.dp).background(p.sunken))
            Row(
                Modifier
                    .fillMaxWidth()
                    .heightIn(min = 40.dp)
                    .padding(horizontal = 14.dp, vertical = 8.dp)
                    .semantics(mergeDescendants = true) {
                        contentDescription =
                            "${stat.stage.label}: median ${stat.medianMillis} milliseconds, " +
                            "budget $budget, " +
                            if (stat.withinBudget) {
                                "within budget"
                            } else {
                                "${stat.overBudgetMillis} milliseconds over budget"
                            }
                    },
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                Text(
                    stat.stage.label,
                    fontSize = Tokens.BodySmall,
                    color = p.ink,
                    modifier = Modifier.weight(1f),
                )
                // Blush where the median is past the budget ceiling. A p95 outside it is
                // expected and is not marked, or every row would be red.
                Mono(
                    "${stat.medianMillis} ms",
                    if (stat.withinBudget) p.sky.deep else p.blush.deep,
                    Tokens.Label,
                    if (stat.withinBudget) FontWeight.Medium else FontWeight.Bold,
                )
                if (!stat.withinBudget) {
                    Icon(
                        Icons.Alert,
                        contentDescription = null,
                        tint = p.blush.core,
                        modifier = Modifier.size(15.dp),
                    )
                }
            }
        }
    }
}

@Composable
private fun ExportRow(onExportCsv: () -> Unit) {
    val p = palette
    Row(
        Modifier
            .fillMaxWidth()
            .heightIn(min = Tokens.SecondaryAction)
            .background(p.sky.tint, RoundedCornerShape(Tokens.RadiusTile))
            .border(Tokens.Hairline, p.sky.mid, RoundedCornerShape(Tokens.RadiusTile))
            .clickable { onExportCsv() }
            .padding(horizontal = 16.dp)
            .semantics(mergeDescendants = true) { contentDescription = "Export the three result files" },
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        Icon(Icons.Download, contentDescription = null, tint = p.sky.core, modifier = Modifier.size(22.dp))
        Column(verticalArrangement = Arrangement.spacedBy(2.dp)) {
            Text("Export CSV", fontSize = Tokens.BodySmall, fontWeight = FontWeight.SemiBold, color = p.sky.deep)
            // Naming the three files matters: "export" alone leaves a reader wondering which
            // numbers they are about to be handed.
            Mono("latency · resource · scorecard", p.muted)
        }
    }
}
