package org.itantra.app.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import org.itantra.bench.LatencySummary
import org.itantra.bench.StageSummary
import org.itantra.bench.UtteranceTrace

/**
 * The metrics screen. Task **W8.1**.
 *
 * ## Why an operational product carries a metrics screen at all
 *
 * Because the alternative is a slide. Every latency and compression figure in this
 * submission is generated by the code that produced it, and this screen is where a jury
 * can watch that happen rather than take it on trust — press the button, speak, and see the
 * number move. A figure that can be reproduced in the room is worth more than a figure that
 * was measured properly last week.
 *
 * ## The screen refuses to quote an unreportable figure
 *
 * `docs/EVALUATION.md` section 1 asks for a hundred utterances minimum, median and p95,
 * never a single run. Below that this screen shows the sample count and the words *not
 * reportable* instead of a number — because a plausible-looking millisecond figure on a
 * device screen is exactly the sort of thing that gets photographed and quoted, and by then
 * nobody remembers it came from nine utterances on a cold handset.
 *
 * That refusal is the feature. It costs nothing when the run is real.
 *
 * ## Three views, because one number cannot carry the argument
 *
 * The headline median answers "how fast". The **stage table** answers "where did the time
 * go", which is what makes a slow run actionable — a slow decode is a thermal problem and a
 * slow link is a radio problem, and they have opposite remedies. The **histogram** answers
 * "is it consistent", and it is the only one of the three that can show a bimodal run: two
 * hundred utterances clustered at 900 ms and 1 800 ms have a respectable median and a
 * throttling defect, and the table alone would hide it.
 */
@Composable
fun MetricsScreen(
    traces: List<UtteranceTrace>,
    onExportCsv: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val summary = LatencySummary.of(traces)
    val reportable = LatencySummary.isReportable(traces)
    val completed = traces.count { it.endToEndMillis != null }

    Column(
        modifier
            .fillMaxSize()
            .background(Paper)
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
    ) {
        Text("METRICS", fontSize = 22.sp, fontWeight = FontWeight.Bold, color = Ink)
        Spacer(Modifier.height(4.dp))
        Text(
            "$completed utterances this session",
            fontSize = 13.sp,
            color = Muted,
        )
        Spacer(Modifier.height(16.dp))

        Headline(summary, reportable, completed)
        Spacer(Modifier.height(20.dp))

        Text("WHERE THE TIME GOES", fontSize = 14.sp, fontWeight = FontWeight.Bold, color = Ink)
        Spacer(Modifier.height(8.dp))
        StageTable(traces)

        Spacer(Modifier.height(20.dp))
        Text("DISTRIBUTION", fontSize = 14.sp, fontWeight = FontWeight.Bold, color = Ink)
        Spacer(Modifier.height(8.dp))
        Histogram(traces)

        Spacer(Modifier.height(24.dp))
        ExportRow(onExportCsv)
    }
}

/**
 * The headline pair, or the reason there isn't one.
 *
 * Median **and** p95 together, never the median alone: an operator remembers the slowest
 * exchange, not the average one, and a median quoted by itself is the number that makes a
 * system look better than it feels.
 */
@Composable
private fun Headline(
    summary: LatencySummary.Stats?,
    reportable: Boolean,
    completed: Int,
) {
    if (summary == null || !reportable) {
        Column(
            Modifier
                .fillMaxWidth()
                .background(Amber)
                .padding(12.dp)
                .semantics {
                    contentDescription =
                        "Not reportable. $completed of " +
                        "${LatencySummary.MINIMUM_UTTERANCES} utterances collected."
                },
        ) {
            Text("NOT REPORTABLE", fontSize = 18.sp, fontWeight = FontWeight.Bold, color = Color.Black)
            Text(
                "$completed of ${LatencySummary.MINIMUM_UTTERANCES} utterances. " +
                    "A median over fewer is not a median.",
                fontSize = 13.sp,
                color = Color.Black,
            )
        }
        return
    }

    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Figure("MEDIAN", "${summary.medianMillis} ms")
        Figure("P95", "${summary.p95Millis} ms")
        Figure("WORST", "${summary.worstMillis} ms")
    }
}

@Composable
private fun Figure(
    label: String,
    value: String,
) {
    Column(
        Modifier.semantics { contentDescription = "$label $value" },
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Text(value, fontSize = 26.sp, fontWeight = FontWeight.Bold, color = Ink)
        Text(label, fontSize = 12.sp, color = Muted)
    }
}

/** One row per stage, with the budget beside it so a reader need not know it. */
@Composable
private fun StageTable(traces: List<UtteranceTrace>) {
    val stages = StageSummary.byStage(traces)
    if (stages.isEmpty()) {
        Text("No completed utterances yet.", fontSize = 14.sp, color = Muted)
        return
    }

    for (stat in stages) {
        val budget = "${stat.stage.budgetMillis.first}–${stat.stage.budgetMillis.last} ms"
        Row(
            Modifier
                .fillMaxWidth()
                .padding(vertical = 6.dp)
                .semantics {
                    contentDescription =
                        "${stat.stage.label}: median ${stat.medianMillis} milliseconds, " +
                        "budget $budget, " +
                        if (stat.withinBudget) {
                            "within budget"
                        } else {
                            "${stat.overBudgetMillis} milliseconds over budget"
                        }
                },
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(stat.stage.label, fontSize = 14.sp, color = Ink, modifier = Modifier.weight(1f))
            Text(
                "${stat.medianMillis} ms",
                fontSize = 14.sp,
                fontFamily = FontFamily.Monospace,
                // Red where the median is past the budget ceiling. A p95 outside it is
                // expected and is not marked, or every row would be red.
                color = if (stat.withinBudget) Ink else Danger,
                fontWeight = if (stat.withinBudget) FontWeight.Normal else FontWeight.Bold,
            )
            Spacer(Modifier.width(12.dp))
            Text(budget, fontSize = 12.sp, fontFamily = FontFamily.Monospace, color = Muted)
        }
    }
}

/**
 * The distribution as bars.
 *
 * Drawn with sized boxes rather than a charting library: this is one screen, the data is
 * already bucketed, and a dependency here would be carried into the APK for the sake of a
 * bar chart in a diagnostic view.
 */
@Composable
private fun Histogram(traces: List<UtteranceTrace>) {
    val buckets = StageSummary.histogram(traces)
    if (buckets.isEmpty()) {
        Text("Nothing to plot yet.", fontSize = 14.sp, color = Muted)
        return
    }
    val tallest = buckets.maxOf { it.count }.coerceAtLeast(1)

    Column(
        Modifier.fillMaxWidth().semantics {
            // A bar chart read glyph by glyph is noise. The shape, in one sentence.
            val busiest = buckets.maxByOrNull { it.count }!!
            contentDescription =
                "Distribution over ${buckets.sumOf { it.count }} utterances, " +
                "most between ${busiest.fromMillis} and ${busiest.toMillis} milliseconds."
        },
    ) {
        for (bucket in buckets) {
            if (bucket.count == 0 && bucket.fromMillis < buckets.first { it.count > 0 }.fromMillis) {
                // Leading empties carry no information; the gaps between clusters do.
                continue
            }
            Row(Modifier.fillMaxWidth().padding(vertical = 1.dp), verticalAlignment = Alignment.CenterVertically) {
                Text(
                    "${bucket.fromMillis}",
                    fontSize = 11.sp,
                    fontFamily = FontFamily.Monospace,
                    color = Muted,
                    modifier = Modifier.width(48.dp),
                )
                Box(
                    Modifier
                        .fillMaxWidth(bucket.count.toFloat() / tallest)
                        .height(BAR_HEIGHT_DP.dp)
                        .background(if (bucket.count == 0) Paper else Ink),
                )
                Spacer(Modifier.width(6.dp))
                Text("${bucket.count}", fontSize = 11.sp, fontFamily = FontFamily.Monospace, color = Muted)
            }
        }
    }
}

@Composable
private fun ExportRow(onExportCsv: () -> Unit) {
    Column(
        Modifier
            .fillMaxWidth()
            .heightIn(min = TARGET_DP.dp)
            .clickable { onExportCsv() }
            .semantics { contentDescription = "Export the three result files" },
    ) {
        Text("EXPORT CSV", fontSize = 16.sp, fontWeight = FontWeight.Bold, color = Ink)
        Text(
            // Naming the three files matters: "export" alone leaves a reader wondering
            // which numbers they are about to be handed.
            "latency.csv, resource.csv, scorecard.csv — each naming this device and soak",
            fontSize = 12.sp,
            color = Muted,
        )
    }
}

private const val BAR_HEIGHT_DP = 14
private const val TARGET_DP = 64
private val Ink = Color(0xFF101010)
private val Paper = Color(0xFFFFFFFF)
private val Muted = Color(0xFF5F5F5F)
private val Danger = Color(0xFFB3261E)
private val Amber = Color(0xFFF2B705)
